# Generated by Django 5.0.7 on 2024-07-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('Order_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('Pizza', models.CharField(choices=[('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Veggie', 'Veggie')], max_length=50)),
                ('Pizza_size', models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=50)),
                ('Toppings', models.ManyToManyField(blank=True, to='app.toppingmodel')),
            ],
        ),
    ]
