# Generated by Django 5.0.7 on 2024-07-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Pizza',
            field=models.CharField(choices=[('Margherita', 'Margherita'), ('Pepperoni', 'Pepperoni'), ('Veggie', 'Veggie'), ('BBQ Chicken', 'BBQ Chicken'), ('Hawaiian', 'Hawaiian'), ('Buffalo Chicken', 'Buffalo Chicken'), ('Meat Lovers', 'Meat Lovers'), ('Cheese', 'Cheese'), ('Supreme', 'Supreme')], max_length=50),
        ),
    ]
