# Generated by Django 5.0.7 on 2024-07-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_ordermodel_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Order_Number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
