# Generated by Django 5.0.7 on 2024-07-29 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ordermodel_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Pizza',
            field=models.CharField(choices=[('Margherita', 'Margherita 10$'), ('Pepperoni', 'Pepperoni 10$'), ('Veggie', 'Veggie 10$'), ('BBQ Chicken', 'BBQ Chicken 10$'), ('Hawaiian', 'Hawaiian 10$'), ('Buffalo Chicken', 'Buffalo Chicken 10$'), ('Meat Lovers', 'Meat Lovers 10$'), ('Cheese', 'Cheese 10$'), ('Supreme', 'Supreme 10$')], max_length=50),
        ),
    ]
