# Generated by Django 5.0.7 on 2024-07-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_ordermodel_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='Order_Number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
